### ISSUE TITLE
Need more than two TRICKY_GAME_NAME avaliable

### ISSUE THREAD

**Issue by SJang1** [yf-dev/trickybot#2]
For even tricky towers, Windows game name is [Tricky Towers], but in linux it's [trickytowers.x86] seen in Fedora 31.

this seems to make this avaliable for more than two name of games, for now it doesn't detect it is Tricky Towers.

**Comment by rishubil** [comment]
The issue you pointed out seems to need to be fixed.
Supporting more than one game name seems a good idea.

We can probably fix this by changing TRICKY_GAME_NAME to List.
